### ISSUE TITLE
DO NOT USE Fast-Render with GroundDB!!

### ISSUE THREAD

**Issue by satyavh** [GroundMeteor/db#116]
When using template level subscription on a ground DB collection, the following happens sometimes, completely at random: 

First the subscription returns correct, but very shortly after it returns empty. 

Reproduce:

First create a collection and ground it

Use template subscription

```
Template.scan.onCreated ->

  @autorun ->
    self.subscribe 'pipes', ->
      console.log 'subscription', Pipes.find().count()
```

helper
```
Template.scan.helpers
  count: ->
    console.log 'helper', Pipes.find().count()
```

will result in the following logging, but not always (refresh browser a couple of times)

```
subscription 1235
helper 1235
helper 0
```

and then there's nothing you can do anymore with your subscription data because the data is gone...

**Comment by satyavh** [comment]
This actually happens every 2nd browser refresh

**Comment by satyavh** [comment]
Actually, it looks that the subscription doesn't change, but the cursor in the template suddenly returns [](or 0 documents)

**Comment by satyavh** [comment]
OK I've found the cause of this issue.

DO NOT USE Fast-Render with GroundDB. If you use Flow Router, be aware that all routes have Fast Render enabled by default.

**Comment by raix** [comment]
1. Please don't "shout" in issue titles
2. The above example code have nothing to do with fast render or grounddb
3. Use plain javascript when asking for advice on SO
4. Provide a replication repo if filing an issue

I'm closing this issue since is kinda the same as https://github.com/GroundMeteor/db/issues/94

**Comment by satyavh** [comment]
Ok got it, so do you want me to make a new issue? 

Because no matter the shouting, code and coffeescript, the combination fast-render + grounddb still doesn't work.

**Comment by raix** [comment]
@satyavh Have you tried https://github.com/GroundMeteor/db#additional-api - Ground db respects subscriptions - therefor unsubscriptions too - but you can take control of this by driving "manually".
(Ground db would trigger a removal of all "local only" documents when all subscriptions were done - but if you want lazy loading etc. subscriptions would not be ready or even start by that time - therefor you might suffer a loss of local data)

*I'm currently working on a new version for meteor 1.2 es2015 version - this will act a bit differently.*

**Comment by satyavh** [comment]
No I haven't. I simply removed Fast Render and that solved all our problems. I will give this a shot.
