### ISSUE TITLE
Uncaught Error: use "new" to construct a Mongo.Collection (if collection-hooks are installed)

### ISSUE THREAD

**Issue by Jehu** [GroundMeteor/db#119]
Hi,

i try to use a clientside-only GroundDB.

meteor Version 1.1.0.3
ground:db Version 0.3.12 

```
if (Meteor.isClient) {
  Territories = new Ground.Collection('Territories', {
    connection: null
  });
}
```

Error in client console (Chrome):
````
 
Uncaught Error: use "new" to construct a Mongo.Collection
```

Please help.

**Comment by Jehu** [comment]
oh no!
found the problem: package matb33:collection-hooks breaks ground:db

**Comment by Jehu** [comment]
Would be nice to get the the two packages work together.

**Comment by raix** [comment]
Could you give the beta a spin to see if its an issue there too? (Wip)

**Comment by joaopiopedreira** [comment]
Hi @Jehu ,

Try this: remove both packages and install in this order:
- matb33:collection-hooks
- ground:db

then it'll work fine (at the time I wrote this, I was using ground:db 0.3.12 and matb33:collection-hooks 0.7.14)

**Comment by bgrayburn** [comment]
@joaopiopedreira, thanks! that worked
@raix, is the version that joaopiopedreira mentioned (0.3.12) the beta you were referring to?

**Comment by joaopiopedreira** [comment]
Brian, the beta version @raix mentioned is the new ES2015 compliant version of
ground:db. I believe it’s meant for Meteor 1.2.
Link here: https://github.com/GroundMeteor/db/tree/es2015-localforage
It has still some work-in-progress, so let it chill for a while ;-)

On 28 August 2015 at 21:28, Brian Rayburn < notifications@github.com > wrote:
@joaopiopedreira , thanks! that worked
@raix , is the version that joaopiopedreira mentioned (0.3.12) the beta you were
referring to?

**Comment by Jehu** [comment]
@joaopiopedreira thanks for the hint with installation order.
