### ISSUE TITLE
Only subscribe to actual updates - prevent refetching?

### ISSUE THREAD

**Issue by obiwarn** [GroundMeteor/db#126]
I found as WIP in the docs for the new version.
Does the old version do this?

**Comment by raix** [comment]
nope

**Comment by obiwarn** [comment]
Do you have a suggestion/best practice for how to accomplish this behavior with the current version?
Hash over collections or sth?

**Comment by raix** [comment]
so you could handle the "localOnly" yourself - you could subscribe from latest update - question is how you would sync removed docs...

**Comment by obiwarn** [comment]
Thank you. I will think about it.
