### ISSUE TITLE
Make binary files offline accessible 

### ISSUE THREAD

**Issue by Slind14** [GroundMeteor/db#142]
Hey,

I hope that you don't mind me asking about something that might not be the goal of ground db. I figured it is a good place as its users are likely to have been at the same point.

I'm looking for a way to make binary content offline available (mobile android/ios app). In my case this would be audio and image files (up to 100 mb per file). Are you aware of any lib, project whatsoever that accomplishes this, or able to point me in the right direction?

My biggest concern is to be able to stay in control. Meaning the user decides what to store locally, abort downloads..

**Comment by tagrudev** [comment]
Well you have several options

Files are not part of ground db, at least for the moment.

The FileSystem is partially deprecating [issue - link](https://github.com/GroundMeteor/db/issues/24) - the browser vendors are working on a better implementation.

The Indexed Database API, or IndexedDB (formerly WebSimpleDB), is a recommended web browser standard interface for a local database of records holding simple values and hierarchical objects - haven't tried that one on real project.

You can checkout pouchDB as well [link](http://pouchdb.com/).

Lastly my opinion: if you need something like that it would be better to go for a native apps and have full control over the files system.

Todor
