### ISSUE TITLE
Limitation on data size

### ISSUE THREAD

**Issue by JohnAReid** [GroundMeteor/db#143]
I have just install GroundMeteor today and it is working just great - many thanks for such a great product that makes Meteor even better!

My question is there any indication on the data size i.e. number of collections and number of documents it can cope with before it falls over?

**Comment by tagrudev** [comment]
@JohnAReid yes, currently GroundDB is depending on the localstorage of the browser. If localstorage is not supported the groundDB simply work as a normal Meteor.Collection - you can find more on the browser quota [here](http://www.html5rocks.com/en/tutorials/offline/quota-research/).
