### ISSUE TITLE
Is there a way to pause syncing

### ISSUE THREAD

**Issue by mehmedaliosman** [GroundMeteor/db#144]
So here's my situation:
Ground db is working all fine. When in offline mode I upload some files and they are stored locally. After I switch to online mode uploading continues automatically. So far all good, but now I need to implement the functionality to manually resume the upload progress. Is there a way to pause the syncing of concrete collection and resume it later?

**Comment by josephdburdick** [comment]
@mehmedaliosman if there was an answer/solution to this could you share it here?

**Comment by mehmedaliosman** [comment]
@josephdburdick
Well, I actually realised that my problem had nothing to do with Ground db.
Though I found a solution that satisfies the PMs requirements.
For uploading files to mongo we use Collection.FS package and from what I understand once you call insert() you can't pause it. I didn't actually research but I believe that the insertion is asyncronous and when the app is ofline it waits untill there's connection again. So basically what I found as workaround is to extend the  FS.Collection with new method insertLazy (FS.Collection.prototype.insertLazy = function (file, callback) {}) within the Meteor.startup hook (client side). What this insertLazy does is pretty simple - it just checks if the app is offline and if so stores the files in an array, otherwise it just calls the regular insert function. But note that this will work only if the user does not close the tab or refresh the page (that's ok in my case).
I have taught of storing files in localStorage after mime encoding them but it has a few cons.
* In most browser's localStorage is limited to 5MB or even less
* Ground db uses localStroge as well, and I wouldn't want to risk loosing some data because of files
stored there
