### ISSUE TITLE
Using sort()

### ISSUE THREAD

**Issue by martinbnielsen** [GroundMeteor/db#147]
Hi

I tried to sort a using this:

`Exams      = new Ground.Collection('exams',      { connection: null });
return Exams.find().sort(examDate: -1);`

But receive : 
`"sort is not a function"`

Is the mongo db sort() not supported in ground db ?

Brgds
Martin Nielsen

**Comment by Jahdrien** [comment]
On Minimongo "sort" is an option of find and not a function:
> Exams = new GroundCollection('exams', { connection: null });
> return Examsfind(selector, {sort: {examDate:-1}});
>

**Comment by martinbnielsen** [comment]
Thanks Adrien - that worked perfectly, and opened my eyes to the fact that minimongo is handled differently that mongo db.
Martin
