### ISSUE TITLE
Collection type in v2

### ISSUE THREAD

**Issue by rainum** [GroundMeteor/db#165]
Hi guys!

In my team we are trying to use ground:db v2 with [meteor-astronomy](https://github.com/jagi/meteor-astronomy). There is an issue: ground:db v2 after creating new collection with `new Ground.Collection('collectionName')` returns `GroundCollection` instead of `Mongo.Collection` like was in ground:db v1. Astronomy does support only `Mongo.Collection` type.

Is there a way to return proper `Mongo.Collection` in v2? Looking forward to your answer, thanks in advance!

**Comment by raix** [comment]
well - ground db II isn't a Mongo.Collection - it's a LocalCollection at best.
just have the ground db observe the Mongo.Collection - should work fine

**Comment by maxfi** [comment]
@raix would you please able to expand on your previous comment? Are you saying that it's possible to have astronomy work with a grounded collection? Thanks.
