### ISSUE TITLE
ObjectID as _id shows localforage warning

### ISSUE THREAD

**Issue by jefbarn** [GroundMeteor/db#166]
From the localforage code:

    // Cast the key to a string, as that's all we can set as a key.
    if (typeof key !== 'string') {
        console.warn(key +
            ' used as a key, but it is not a string.');
        key = String(key);
    }

Perhaps add an idGeneration flag similar to the Meteor api?

**Comment by raix** [comment]
Let me know if this is still an issue in 2.0.0-rc.5

**Comment by jefbarn** [comment]
I transitioned my project off meteor.  Closing this issue.
