### ISSUE TITLE
"Uncaught TypeError: Ground.Collection is not a constructor" on 1.3.2.4 (did not test below)

### ISSUE THREAD

**Issue by dagatsoin** [GroundMeteor/db#169]
Hi @raix 

it seams that something is broken. I try to use it with the last meteor RC release. I have just created a project and replace the main.js content by:
```
import Ground from 'meteor/ground:db';

const foo = new Ground.Collection('foo');
```

and chrome throw an error:
```
Uncaught TypeError: Ground.Collection is not a constructor
```

**Comment by dagatsoin** [comment]
false alert

**Comment by came** [comment]
I am having the same error. How did you solve it?
Thx

**Comment by came** [comment]
ok, I just had to 
import {Ground} from 'meteor/ground:db'; 
instead of 
import Ground from 'meteor/ground:db';
