### ISSUE TITLE
ES2015 branch doesn't work

### ISSUE THREAD

**Issue by NitroBAY** [GroundMeteor/db#173]
I first started with V2 but as I need to have a full mongo collection for comnpatibility with easysearch I try to use older version. I first give a try to localforage version as, it says to be faster and I already needed around 10 second instead of 2 second when online with V2 (which have localstorage) but it's just not working when I refresh the browser (first time with no cache populated it's working but second time no data !) .
I have tried with simplest code possible : 
`export const Worksheets = new Ground.Collection('worksheets');`

`Template.flow.onCreated(() => {
    Meteor.subscribe('worksheets');
});` 
and a helper who just `return Worksheets.find()`
I also tried to wrap subscribe into worksheet.once('loaded', () => {});
When I switch back to master version, it's all working.
Packages : 
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

fourseven:scss
useraccounts:materialize
accounts-password
kadira:flow-router
kadira:blaze-layout
arillo:flow-router-helpers
useraccounts:flow-routing
softwarerero:accounts-t9n
aldeed:simple-schema
alanning:roles
aldeed:collection2
percolate:momentum
philippspo:momentum-flow-router
materialize:materialize
easysearch:core
matteodem:easy-search
ground:db
PS : I hope one day I could not have to wait 10 second for app loading, maybe I've misunderstand something or is that normal time for a simple DB with 4 row.
PS 2 : BTW if someone want to use service worker instead of the old depreciated appcache to have an offline app by caching assets I made a meteor Service Worker https://github.com/NitroBAY/meteor-service-worker/blob/master/sw.js

**Comment by Illyism** [comment]
Seems to be. Sadly the master branch doesn't work with meteor 1.3 for me.

**Comment by NitroBAY** [comment]
For me it's working with very last meteor version... sorry for you

**Comment by raix** [comment]
Let me know if this is still an issue in 2.0.0-rc.5

**Comment by NitroBAY** [comment]
V2 is working now
