### ISSUE TITLE
Meteor does not currently support objects other than ObjectID as ids

### ISSUE THREAD

**Issue by Mattze96** [GroundMeteor/db#177]
Hello, 

i'm using ground:db from the grounddb-caching-2016 branch.

When accessing external database i get the following error in offline-mode:

    Meteor does not currently support objects other than ObjectID as ids

Is there any fix or wrapper available? The point is, that i'm not able to write into the external collection

**Comment by raix** [comment]
Mongo.Collection has a property called `idGeneration='STRING'`

**Comment by Mattze96** [comment]
no, not working with that.

    KeyValueStore = new Mongo.Collection('keyvaluestore'); 
    Test = new Mongo.Collection('test', {idGeneration: 'STRING'});

Example documents:

*KeyValueStore*

    { "_id" : "hits", "val" : 388974 }

*Test*

     { "_id" : ObjectId("55b5f86f7b2179e52b21300c"), "val" : "foobar"}

KeyValueStore is not causing any errors, but Test does. I think it has to do something with ObjectId().

**Comment by raix** [comment]
Yes - I don't think objectId is supported on the client by Meteor.Collection
https://github.com/meteor/meteor/issues/4193

**Comment by raix** [comment]
https://github.com/meteor/meteor/issues/6219

A possible explanation in:
https://github.com/GroundMeteor/db/issues/99#issuecomment-189903236

**Comment by Mattze96** [comment]
thanks, so it is no bug in ground:db.

I came up with a really dirty fix. I think it isn't even efficient...

```
  Meteor.publish('miniplans', function(argument){
    var self = this;
    Test.find().forEach(function(doc) {
      self.added('test', doc._id._str, doc);
    });
    self.ready();
  });
```

**Comment by raix** [comment]
It autoclosed... Let me know if this is still an issue in 2.0.0-rc.5 :)
