### ISSUE TITLE
ground:db@2.0.0 convert Date to String

### ISSUE THREAD

**Issue by aldeed** [GroundMeteor/db#178]
If I put a `find()` in an autorun, all properties that should be `Date` type are instead `String` type until the real data arrives from the server.

Happens on ground:db@2.0.0-rc.3 and ground:db@2.0.0-rc.4 with Meteor 1.4.1. I haven't tried earlier RCs.

**Comment by raix** [comment]
It autoclosed... Let me know if this is still an issue in 2.0.0-rc.5 :)

**Comment by aldeed** [comment]
@raix just wanted to mention that this seemed to still be happening with 2.0.0-rc.5. We disabled offline for now, but hopefully can get back to this and make a reproduction or something.

**Comment by raix** [comment]
Did you reset the local db?

**Comment by aldeed** [comment]
@raix I manually wiped local storage, but now that you mention it, it doesn't use local storage anymore does it? What's the correct way to wipe?

**Comment by raix** [comment]
right - it might user indexed db or websql etc. depending on the browser - 2.0.0-rc.5 uses ejson types so it should preserve dates. But I'll have another look at it

**Comment by raix** [comment]
@aldeed just tried to start up my "ground-qa" app - but the meteor tool hangs, not sure if mdg broke something... I'll try again in a couple of days
