### ISSUE TITLE
Some data disappears/reappears  

### ISSUE THREAD

**Issue by NitroBAY** [GroundMeteor/db#184]
Hello,
I had bugs since weeks when I use grounddb that I don't have with default minimongo integrated in Meteor. I first taught it was Easysearch which was at the origin of the bug so I did create my own search engine after weeks waste trying to understand what was wrong with grounddb/Easy Search. Now I'm creating my own client search engine I have the same problem. I just understand why and it's coming from ground:db 
http://i.imgur.com/OWr6RAl.png
This is my grounded collection of Meteor.users and as you can see after localUser (ground version Meteor.users) is ready the data I subscribed too 

```
  Meteor.subscribe('userWorksheets');
  Meteor.subscribe('billing');
```

(worksheets and billing) disappears and reappears in so a short moment that blaze drives crazy and my website partially stops working. I hope @raix or anyone could help me on that.
Please note that I don't have such problem with native collections and to be short I expect grounddb to be less unpredictable.

**Comment by raix** [comment]
what version are you using? (you can experience the same thing with regular meteor collections... might want to checkout https://atmospherejs.com/meteorhacks/subs-manager)

**Comment by NitroBAY** [comment]
I use 2.0.0-rc.5
    console.log(Meteor.user(), localUser.findOne());

undefined
{emails: Array[1], _id: "46CzcyYYE6u9vJpS9", roles: Array[1], worksheets: Object, billing: Object}

{_id: "46CzcyYYE6u9vJpS9", emails: Array[1], roles: Array[1]} 
{emails: Array[1], _id: "46CzcyYYE6u9vJpS9", roles: Array[1]}

{_id: "46CzcyYYE6u9vJpS9", emails: Array[1], roles: Array[1], worksheets: Object, billing: Object}
{emails: Array[1], _id: "46CzcyYYE6u9vJpS9", roles: Array[1], worksheets: Object, billing: Object}

**Comment by NitroBAY** [comment]
I open an issue on Blaze as the problem is the compatibility between Blaze and ground:db because one is updating too fast for nothing and the other cannot follow the speed of the updating https://github.com/meteor/blaze/issues/145

**Comment by NitroBAY** [comment]
Please see https://github.com/meteor/blaze/issues/146 also and my reproduction here https://github.com/NitroBAY/ground-blaze-bug-repro

**Comment by raix** [comment]
I don't think it's a Blaze issue - I'm thiniing it's a dispatch:kernel issue (I should improve that package)

**Comment by NitroBAY** [comment]
hmm okay so you're telling me that all the problems that drives me to become to hate Meteor (can't use autorun(), can't use #each with grounddb collections) came all from this lovely dispatch:kernel ?? Damn then I don't know nobody ever noticed it altough a lot of ppl downloaded your package. In any way I hope you'll fix that ASAP. Thanks a lot for your work and your support in any way @raix ❤️

**Comment by NitroBAY** [comment]
You should maybe create a branch dispatch:kernel-free before working on fixing it ?

**Comment by NitroBAY** [comment]
In anyway although it's bit obscure exactly how the package is working to optimize Meteor for a muggle like me can I ask you why didn't you make a PR to Meteor and Blaze ? If it's good for performance and it's backward compatible it should be merged.

**Comment by NitroBAY** [comment]
@raix any ETA, you may want to create a branch kernel-free for those who really need a fix like me ?

**Comment by NitroBAY** [comment]
@raix ?

**Comment by raix** [comment]
@NitroBAY try ground:db@2.0.0-rc.6

**Comment by NitroBAY** [comment]
Great, finally I'll give a try right now

**Comment by NitroBAY** [comment]
Got it

**Comment by raix** [comment]
you should be able to bump the version directly in `.meteor/packages`

**Comment by NitroBAY** [comment]
What ? I was cloning your repo until now as I thought I had to do that because on Atmosphere it's still pre v1.

**Comment by NitroBAY** [comment]
Okay I will need some time to make checks (especially that I was making not backward compatible updates so I had to reset database). Thanks @raix you're great, we're lucky to have you.

**Comment by raix** [comment]
@NitroBAY lack of time - it takes time to do a pr. I might talk with @mitar about it or wait for react fibers which tries to solve the same issue

**Comment by raix** [comment]
@NitroBAY did it solve your issue? (I saw that you had nested blaze autoruns in your render function - was that causing the issue with the kernel? (cause that might be an issue in kernel)

**Comment by mitar** [comment]
Oh, I am sad to read that using kernel has bad side-effects. Because that is one of things I was planing to integrate into Blaze/Tracker at some point. It seems like a reasonable thing to do. But probably it really can have some side-effects.

**Comment by NitroBAY** [comment]
@raix it did solves this issue (also see https://github.com/meteor/blaze/issues/146) and besides it fix #101, thanks !! @mitar maybe you and @raix can play with my reproduction https://github.com/NitroBAY/ground-blaze-bug-repro to understand what's wrong ?

**Comment by raix** [comment]
Thanks Ill investigate, we should have the kernel working as it unblocks the ui

**Comment by mitar** [comment]
What I would do is make `Tracker.flush` be blocking, but the normal autorun be non-blocking. And explain that if you use `Tracker.flush` you loose the advantages of kernel.

Also, in the latest Blaze version I released, I relaxed Blaze requirements about [nested autoruns](https://github.com/meteor/blaze/blob/master/HISTORY.md).

**Comment by NitroBAY** [comment]
My issue with autorun was that `this.autorun ` eventually was not working whereas `Tracker.autorun` was always (I think) working. Maybe that `this.autorun` was especially not working in nested templates.

**Comment by NitroBAY** [comment]
I close, even tough you have very interesting discussion, this issue is fix in ground:db as RC6 removed dispatch:kernel, but dispatch kernel was the one who has problems with autorun as you know : see https://github.com/DispatchMe/meteor-kernel/issues/6.

**Comment by maxfi** [comment]
@raix is there any chance that `dispatch:kernel` could be removed from v0.3.15? Unfortunately I cannot use v2 in my project as it breaks compatibility with other packages due to grounded collection being an instance of `LocalCollection` instead of `Mongo.Collection`.
