### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by barisro** [GroundMeteor/db#187]
Hi @raix ,

I am using 2.0.0-rc.6 with Meteor 1.4.2.1 and have "Cannot call a class as a function" error. 
Can you please help or point me to right direction to fix this ?

Thank you in advance

**Comment by raix** [comment]
use new?

**Comment by barisro** [comment]
That was the problem. But I am kind of confused; can we still have only one collection and have a mongo collection grounded ? 
Thank you

**Comment by barisro** [comment]
Thank you.
