### ISSUE TITLE
Using pendingReads & pendingWrites

### ISSUE THREAD

**Issue by Baralabite** [GroundMeteor/db#199]
G'day,

I'm having difficulty figuring out how to use pendingReads & pendingWrites. I'm using version 0.3.15 from atmosphere.

I have tried running Ground.pendingWrites & new Ground.Collection().pendingWrites - both return undefined.

I find this confusing after reading the source as "eventemitter" and "pendingWrite" both have the same scope, yet I can see eventemitter, but not pendingWrite on a Ground.Collection instance.

Regards,

John

**Comment by raix** [comment]
Hi, you have to use v2 rc
