### ISSUE TITLE
Corrupted data after hot code push

### ISSUE THREAD

**Issue by vjau** [GroundMeteor/db#78]
Hi,
when storing objects with methods in a pure client side collection, very often the data becomes corrupted (key and values are swapped randomly) after a hot code push.
Steps to reproduce:
```JS
//create a base project with meteor create 

//create a pure client side ground collection
testColl = new Ground.Collection('testColl', { connection: null });

//go in the console and create an object with methods:
var obj =  {a:1, b:function(){return "foo";},c:function(){return "bar";}};

//insert it in the collection
testColl.insert(obj);

//Modify a line in your code to force a hot code push.
//Then in the reloaded console, do a 
testColl.find().fetch()

//The object will be corrupted.

```
Strange thing is that if you try it again with the same object it work, but then adding an object with more methods and keys will get you again a corrupted object after hot code push.

**Comment by vjau** [comment]
Updated report, you need an object with two methods.

**Comment by raix** [comment]
So if you dont have functions in the object you insert its working? - It should actually throw an error, functions are not jsonable/ejson - so the behaviour is expected, but it should throw an error.

I'm not 100% sure why it doesn't fail - it could be that the MiniMax.minify tries to reason about this - it should just skip functions.

**Comment by raix** [comment]
Edit: minify should actually dont skip - it should just insert the function - have to investigate if its iterating over function properties.

**Comment by vjau** [comment]
"So if you dont have functions in the object you insert its working? - It should actually throw an error, functions are not jsonable/ejson - so the behaviour is expected, but it should throw an error."

IMHO it should not throw, but just drop the keys corresponding to functions, like regular meteor collection.
I have tried to do a EJSON.parse(EJSON.stringify(obj)) before insert, but i'm still not 100% sure that this is correcting my problem. I need a tad more experimenting.

**Comment by vjau** [comment]
Actually in my app, when i insert a pure data object without functions (through EJSON parse/stringify "filtering"), it doesn't persist through hot code push, althought it could be due to a bug on my part.
I dont know if ground db is designed to persist the data between HCP. I'm trying to replace the meteor Session with a client only ground db collection, as a mean to do session persistance of my objects.

**Comment by vjau** [comment]
My findings show that once you have a corrupted document in the grounddb, it goes berserk, and is never considered loaded.
So it's not only corrupting the document but also the whole grounded db.

**Comment by vjau** [comment]
Only solution after the corruption has occured is to clear the whole localstorage. Perhaps there should be some validation (?) to ensure one faulty document can't doom the whole grounddb ?

**Comment by vjau** [comment]
Please take a look at my PR:
https://github.com/GroundMeteor/minimax/pull/3
It can have a performance penalty but i think it's worth it.

**Comment by raix** [comment]
Thanks but I hope its fixed now?

**Comment by vjau** [comment]
No, it doesn't work.
Please take a look at my test added in my pull request.

**Comment by raix** [comment]
ground:db@0.3.3
