### ISSUE TITLE
Example with iron-router?

### ISSUE THREAD

**Issue by almogdesign** [GroundMeteor/db#84]
Hi, 
I wanted to know if you had an example using GroundDB and iron-router. Noting that I try seems to be working.

**Comment by almogdesign** [comment]
I'm closing this, my current workaround seems to be working

**Comment by Anonyfox** [comment]
what's your workaround?

**Comment by almogdesign** [comment]
Just did a simple check (getConnectionStatus()) to see if the user has a connection or not 

Router.route('notifications', {
    path: '/notifications',
    layoutTemplate: 'layoutApp',
    waitOn: function(){
        if(getConnectionStatus() && Meteor.user()) {
            return [Meteor.subscribe('organizations'), Meteor.subscribe('notifications')];
        } else {
            this.render();
        }
    }
});

**Comment by Anonyfox** [comment]
thanks!
