### ISSUE TITLE
How and why use grounddb ?

### ISSUE THREAD

**Issue by stivaugoin** [GroundMeteor/db#93]
I don't understand how to use this package. I'd read the documentation and some very basic example, but when I try, I have the same behavior as meteor without package. Maybe I don't understand the use case hehe. Please, just tell me if my use case will work with grounddb

I have a mobile application with a survey (5-6 basics questions). Users will download the application on Play Store and when they are open, it will not have a connection. They will respond to the survey.

If the application is not closed, the data is transferred well to servers when connection is restored. 
However, if the user closes the application, I would like that the data is transferred when it opens a connection with its application.

But now, when I try this use case, all client data is cleared when I open the application.

Is it possible? Please tell me yes :D 

Thanks!

**Comment by rafaelquintanilha** [comment]
@stivaugoin you might want to have a look at this repo: https://github.com/rafaelquintanilha/meteor-offline

For long I had the same feeling, kind of lost in how to user GroundDB properly. In this repo I just set you can check how to play with the package and have your data persistently stored.

**Comment by stivaugoin** [comment]
@rafaelquintanilha thank you very much! I will try this soon

**Comment by raix** [comment]
Great work @rafaelquintanilha looks good, @stivaugoin sorry about the lack of response, I'm just low on time at the moment
