### ISSUE TITLE
Question about `methodResume`

### ISSUE THREAD

**Issue by DavidSunny** [GroundMeteor/db#96]
```
  // This is how grounddb uses this internally
  Ground.methodResume([
    '/' + self.name + '/insert',
    '/' + self.name + '/remove',
    '/' + self.name + '/update'
  ], self.connection);
```

I am trying to make it so that the client remembers a certain method, in my case, a method called 'blogInsert'. So this is my scenario.

(when connection is ON)
1. User inputs blog post and then saves.
2. The method `blogInsert` is called.
3. `blogInsert` validates object and inserts into `Blogs = new Mongo.Collection('blogs');`

(when connection is OFF)
1. User inputs blog post and then saves.
2. The method `blogInsert` is called.
3. Client remembers to call `blogInsert`.  <- I think it doesn't do this.
4. Connection is recovered. <- From here the inserted blog post does not show.
5. Client calls `blogInsert`.
6. `blogInsert` validates object and inserts into `Blogs = new Mongo.Collection('blogs');`

But so far I haven't been able to figure out how to make the scenario work when connection is offline. 

I have defined `Ground.Collection(Blogs);` already.

So I'm assuming that I have to use `methodResume` in this scenario. However, I couldn't quite understand how to use it. Could you give me some guidance on how I could use `Ground.methodResume`?

Thank you in advance.

**Comment by Jehu** [comment]
Do you use a callback with your method call?

This works for me offline: 
```
Meteor.call('addTerritory', insertDoc);
Router.go('territories');
```
while this is not working offline, but online:
```
Meteor.call('addTerritory', insertDoc, function(err, res) {
  if(!err) { Router.go('territories'); }
});
```
Sync (when online again) works too without using the callback.

**Comment by DavidSunny** [comment]
Jehu, thank you. I'll try it. :)
