### ISSUE TITLE
Error: Meteor does not currently support objects other than ObjectID as ids - v0.3.9

### ISSUE THREAD

**Issue by jadsonlourenco** [GroundMeteor/db#99]
After upgrade to new version I saw that this package now use more two dependencies: **dispatch:kernel** and **dispatch:request-animation-frame**, and get this error on client side:
````
Uncaught Error: Meteor does not currently support objects other than ObjectID as ids
```
But I not get this error with "users" collection, just with normal collection.

Thanks!

**Comment by jadsonlourenco** [comment]
Well, I don't know why but "MongoLab" editor add **$oid** to "_id" on insert, and removing it solve the issue.

**Comment by raix** [comment]
seems odd - the kernel doesn't touch the data,

**Comment by jadsonlourenco** [comment]
True, very strange. I solve it in my case, but left open because maybe has a solution without edit the content of the database. But I will close it now, if I find a better solution come here to share.

Thanks!

**Comment by awwx** [comment]
You'll get this error if you insert documents in Mongo without specifying the document _id.  (Meteor generates a document _id if it isn't specified by the user, so you won't see this when inserting from Meteor).

If you insert a document from Meteor, it will look like this:

```
meteor:PRIMARY> db.foo.find()
{ "_id" : "oLvboPHawX9wSYpEM", "name" : "one" }
```

But, if you insert a document from Mongo without specifying the _id,

```
meteor:PRIMARY> db.foo.insert({name: "one"})
WriteResult({ "nInserted" : 1 })
```

it will end up looking like this:

```
meteor:PRIMARY> db.foo.find()
{ "_id" : ObjectId("56d321cd333854e7589aa176"), "name" : "one" }
````

and on the client you'll get the "Meteor does not currently support objects other than ObjectID as ids" error when using foo as a ground collection.

(I suspect that clients that construct document id's using http://docs.meteor.com/#/full/mongo_object_id would also get the error, but I haven't tried it).
